### ISSUE TITLE
Hacktoberfest 2024

### ISSUE THREAD

**Issue by naitiklovestech** [parthasarathy27/Hacktoberfest2024#34]
Hello there,
I wish to contribute programs to Java folder regarding recursion, greedy algorithms, knapsack algorithms and dynamic programming

Kindly assign that to me

Peace ✌️

**Comment by herambchaudhari4121** [comment]
I hope you are doing well. I recently submitted a pull request (PR) to your project as part of Hacktoberfest, and I would be grateful if you could take a moment to review it.
#1
PR link: https://github.com/herambchaudhari4121/Hacktoberfest24/pull/1

If any changes or improvements are needed, please let me know, and I would be happy to address them.

Thank you for maintaining such a great project, and I look forward to your feedback.
